spring:
  application:
    name: USER-SERVICE

  data:
    mongodb:
      uri: ${mongo_uri}
      database: ThePetClub
      auto-index-creation: true
      username: ${mongo_username}
      password: ${mongo_password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  secretKey: ${secret_key}

twilio:
  accountSID: ${account_SID}
  authToken: ${auth_Token}
  phoneNumber: ${phone_Number}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  PORT: 8080
